// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTAssignment.Data;

#nullable disable

namespace RESTAssignment.Migrations
{
    [DbContext(typeof(RESTAssignmentDbContext))]
    [Migration("20260118170251_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RESTAssignment.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Long walks in nature and challenging terrain",
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Creating delicious meals and experimenting with recipes",
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Capturing moments through the lens of a camera",
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Playing video games across various platforms",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Exploring new places and experiencing different cultures",
                            Name = "Traveling"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Diving into books and expanding knowledge",
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Listening to and creating music across genres",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Engaging in physical activities to maintain health and wellness",
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cultivating plants and creating beautiful outdoor spaces",
                            Name = "Gardening"
                        });
                });

            modelBuilder.Entity("RESTAssignment.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1,
                            Url = "https://www.visitstockholm.com/see-do/activities/hiking-trails/"
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            PersonId = 2,
                            Url = "https://cooking.nytimes.com/"
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 4,
                            PersonId = 3,
                            Url = "https://www.ign.com/"
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 5,
                            PersonId = 4,
                            Url = "https://www.lonelyplanet.com/"
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 7,
                            PersonId = 5,
                            Url = "https://www.spotify.com/"
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 3,
                            PersonId = 1,
                            Url = "https://www.nationalgeographic.com/photography"
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 6,
                            PersonId = 2,
                            Url = "https://www.goodreads.com/"
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 8,
                            PersonId = 3,
                            Url = "https://www.fitnessblender.com/"
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 9,
                            PersonId = 4,
                            Url = "https://www.gardeningknowhow.com/"
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 1,
                            PersonId = 5,
                            Url = "https://www.alltrails.com/"
                        },
                        new
                        {
                            Id = 11,
                            InterestId = 9,
                            PersonId = 2,
                            Url = "https://www.rhs.org.uk/"
                        },
                        new
                        {
                            Id = 12,
                            InterestId = 8,
                            PersonId = 5,
                            Url = "https://www.bodybuilding.com/"
                        },
                        new
                        {
                            Id = 13,
                            InterestId = 5,
                            PersonId = 1,
                            Url = "https://www.tripadvisor.com/"
                        },
                        new
                        {
                            Id = 14,
                            InterestId = 7,
                            PersonId = 2,
                            Url = "https://www.rollingstone.com/music/"
                        },
                        new
                        {
                            Id = 15,
                            InterestId = 1,
                            PersonId = 3,
                            Url = "https://www.hikingproject.com/"
                        },
                        new
                        {
                            Id = 16,
                            InterestId = 2,
                            PersonId = 4,
                            Url = "https://www.allrecipes.com/"
                        },
                        new
                        {
                            Id = 17,
                            InterestId = 3,
                            PersonId = 5,
                            Url = "https://www.digitalphotomentor.com/"
                        },
                        new
                        {
                            Id = 18,
                            InterestId = 5,
                            PersonId = 4,
                            Url = "https://www.nationalgeographic.com/travel/"
                        },
                        new
                        {
                            Id = 19,
                            InterestId = 6,
                            PersonId = 2,
                            Url = "https://www.projectgutenberg.org/"
                        },
                        new
                        {
                            Id = 20,
                            InterestId = 8,
                            PersonId = 3,
                            Url = "https://www.myfitnesspal.com/"
                        });
                });

            modelBuilder.Entity("RESTAssignment.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            LastName = "Smith",
                            Phone = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Bob",
                            LastName = "Brown",
                            Phone = "444-987-6543"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Charlie",
                            LastName = "Davis",
                            Phone = "333-222-1111"
                        });
                });

            modelBuilder.Entity("RESTAssignment.Models.PersonInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 3,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 5,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 2,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 6,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 7,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 9,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 1,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 4,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 8,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 11,
                            InterestId = 2,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 12,
                            InterestId = 5,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 13,
                            InterestId = 3,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 14,
                            InterestId = 7,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 15,
                            InterestId = 9,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 16,
                            InterestId = 8,
                            PersonId = 5
                        });
                });

            modelBuilder.Entity("RESTAssignment.Models.Link", b =>
                {
                    b.HasOne("RESTAssignment.Models.Interest", "Interest")
                        .WithMany("LinksAbout")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RESTAssignment.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RESTAssignment.Models.PersonInterest", b =>
                {
                    b.HasOne("RESTAssignment.Models.Interest", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RESTAssignment.Models.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RESTAssignment.Models.Interest", b =>
                {
                    b.Navigation("LinksAbout");

                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("RESTAssignment.Models.Person", b =>
                {
                    b.Navigation("PersonInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
